### ISSUE TITLE
Can't get this to work running Mac OS X 10.10.3 (14D136)

### ISSUE THREAD

**Issue by itsbrex** [fractaledmind/alfred_snippets#1]
Appears to run, but nothing expands.

**Comment by fractaledmind** [comment]
Can you turn on Alfred's debugger before running the workflow, then put the logged output here?

**Comment by itsbrex** [comment]
Problem solved. User error  – 

When I was creating the snippet dictionary with `snip:d` I was including the `,,` before the abbreviation. (i.e. `snip:d ,,db: debugger ,,wf: workflow`) Looked at the demo again and saw that your example didn't include those. Removing them solved the problem immediately. 

One question tho - how do you get the abbreviations to each be on their own line like in the demo?
Or, did you just do that manually?

EDIT: I just tried wrapping the dictionary abbreviations with ^^^ manually and then snipping and is didn't work. Debugger log below:

```
Starting debug for 'Snippets'

[ERROR: alfred.workflow.action.script] 08:07:38 workflow.py:1275 ERROR    too many values to unpack
Traceback (most recent call last):
  File "/Users/brianroach/Dropbox/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.95EBD56B-8C04-42DF-89F6-C266C7496356/workflow/workflow.py", line 1273, in run
    func(self)
  File "snippets.py", line 91, in main
    clean_str = expand_snippets(_str)
  File "snippets.py", line 65, in expand_snippets
    [key, val] = i.split(':')
ValueError: too many values to unpack
```

**Comment by fractaledmind** [comment]
`snip:d` is a shortcut for creating multi-line snippet dictionaries. As the documentation states, multi-line snippet dictionaries have `^^^` on their own line, with the snippet pairs on lines between:

```
^^^
key:value
other:second
^^^
```

If you want to use a single-line dictionary, the `^^^` are on one line with a _single_ snippet pair between:

```
^^^key:value^^^
```

**Comment by itsbrex** [comment]
Okay, great. Just tried that out and it all is working. I was just making the multi-line dictionary manually before. 

Thanks!
